# 1] Import Dependencies

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)

#regular expression
import re

#extract data 
import glob
import docx
import doc

import spacy 
from spacy.matcher import Matcher
# load pre-trained model
nlp = spacy.load('en_core_web_sm')
import warnings
warnings.filterwarnings("ignore")

# 2] Creating dataset from all the resumes

In [2]:
path1 = 'F:\\Data Science\\Projects\\NLP\\Resumes\\SQL Developer Lightning insight'
path2 = 'F:\\Data Science\\Projects\\NLP\\Resumes\\React Developer'
path3 = 'F:\\Data Science\\Projects\\NLP\\Resumes\\Peoplesoft resumes'
path4 = 'F:\\Data Science\\Projects\\NLP\\Resumes\\workday resumes'

sql=glob.glob(path1 + "/*.docx")
react=glob.glob(path2 + "/*.docx")
ppl=glob.glob(path3 + "/*.docx")
work=glob.glob(path4 + "/*.docx")

In [3]:
def readtxt(filename):
    doc = docx.Document(filename)
    fullText = []
    for para in doc.paragraphs:
        fullText.append(para.text)
    return '\n'.join(fullText)

In [4]:
Resume1=[]
Category1=[]
for filename in sql:
    dummy1=readtxt(filename)
    Resume1.append(dummy1)
    Category1.append("SQL Developer")
    SQL = (pd.DataFrame(Resume1,Category1).reset_index())
    SQL.columns = ['Category','Resume']


Resume2=[]
Category2=[]
for filename in react:
    dummy2=readtxt(filename)
    Resume2.append(dummy2)
    Category2.append("React JS Developer")
    reactjs = (pd.DataFrame(Resume2,Category2).reset_index())
    reactjs.columns = ['Category','Resume']
    

Resume3=[]
Category3=[]
for filename in ppl:
    dummy3=readtxt(filename)
    Resume3.append(dummy3)
    Category3.append("Peoplesoft")
    Peoplesoft = (pd.DataFrame(Resume3,Category3).reset_index())
    Peoplesoft.columns = ['Category','Resume']


Resume4=[]
Category4=[]
for filename in work:
    dummy4=readtxt(filename)
    Resume4.append(dummy4)
    Category4.append('Work Day')
    workday = (pd.DataFrame(Resume4,Category4).reset_index())
    workday.columns = ['Category','Resume']


df = pd.concat([SQL,reactjs, Peoplesoft, workday],axis=0).reset_index()
df = df.drop(columns='index',axis=0)
df['Resume']= df['Resume']
df.head()

        Category                                             Resume
0  SQL Developer  ANIL KUMAR MADDUKURI  \t\t\nSQL & MSBI Develop...
1  SQL Developer  \nAradhana Tripathi\n\nCurrent Location: Gachi...
2  SQL Developer  BUDDHA VAMSI                                  ...
3  SQL Developer  KAMBALLA PRADEEP                              ...
4  SQL Developer  \n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...

# 3] Creating functions to extract data from Resume column

In [5]:
def extract_name(text):
    nlp_text = nlp(text)

    matcher = Matcher(nlp.vocab)
    pattern = [{'POS':'PROPN','POS':'PROPN'}]
    matcher.add('PERSON', [pattern])
    matches = matcher(nlp_text)
    for match_id, start, end in matches:
        span = nlp_text[start:end]
        return span.text

df['Name'] = df['Resume'].apply(extract_name)
df['Name'] = df['Name'].str.strip()
df

,Category,Resume,Name
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana
2,SQL Developer,BUDDHA VAMSI ...,IT
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad
5,SQL Developer,\n Res...,Resume
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL
7,SQL Developer,SQL SER...,SQL
8,SQL Developer,SQL SER...,SQL
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU
10,SQL Developer,resume\n\n...,Ramalakshmi
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.
14,React JS Developer,Name: Ravali P \n\n ...,Ravali
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090"
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft
44,Peoplesoft,Vinod Akkala ...,Vinod
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft
52,Peoplesoft,\nR Ahmed ...,R
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari
58,Work Day,Harikrishna Akula ...,Harikrishna
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU
60,Work Day,\n ...,G
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh
70,Work Day,Shireesh Balasani ...,Shireesh
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu
75,Work Day,...,Vinay

In [6]:
def extract_skills(text, category):
    skills = []
    if category == 'SQL Developer':
        predefined_skills = ['SQL', 'ETL', 'Stored Procedures', 'Database Management', 'Data Analysis', 
                             'Query Optimization', 'Performance Tuning', 'Data Modeling', 
                             'Indexing', 'Data Warehousing']
    
    elif category == 'Work Day':
        predefined_skills = ['Workday', 'HCM', 'Integration', 'Consultant', 'Business Processes', 
                             'Configuration', 'Report Writing', 'Security Administration', 'Absence Management', 'Benefits Administration']
    
    elif category == 'Peoplesoft':
        predefined_skills = ['Peoplesoft', 'HRMS', 'Payroll Management', 'PeopleTools',
                             'Application Designer', 'PeopleCode', 'Component Interface', 'SQR', 
                             'Integration Broker', 'Workflow']
    
    elif category == 'React JS Developer':
        predefined_skills = ['React JS', 'UI Development', 'MERN stack','JavaScript', 'JSON',
                              'React','HTML', 'CSS', 'RESTful APIs', 'React Router', 'Redux', 
                             'Webpack', 'Testing (Jest/Enzyme)']
    else:
        predefined_skills = []

    for skill in predefined_skills:
        pattern = r'\b{}\b'.format(re.escape(skill), flags=re.IGNORECASE)
        if re.search(pattern, text, flags=re.IGNORECASE):
            skills.append(skill)

    return ', '.join(skills[:10])

# Apply the function to the DataFrame based on the Category column
df['Skills'] = df.apply(lambda x: extract_skills(x['Resume'], x['Category']), axis=1)
df

,Category,Resume,Name,Skills
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL,"SQL, ETL, Stored Procedures"
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana,"SQL, Stored Procedures, Database Management, D..."
2,SQL Developer,BUDDHA VAMSI ...,IT,"SQL, ETL, Stored Procedures"
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA,"SQL, Stored Procedures, Database Management"
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad,"SQL, ETL, Stored Procedures"
5,SQL Developer,\n Res...,Resume,"SQL, Stored Procedures"
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL,"SQL, Stored Procedures, Query Optimization, Pe..."
7,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning"
8,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning"
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU,"SQL, Stored Procedures, Performance Tuning"
10,SQL Developer,resume\n\n...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing"
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning"
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience,"SQL, Stored Procedures, Performance Tuning"
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.,"SQL, ETL, Stored Procedures"
14,React JS Developer,Name: Ravali P \n\n ...,Ravali,
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN,"JavaScript, HTML, CSS"
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ..."
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS"
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H..."
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen,"MERN stack, HTML, CSS"
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE,"JavaScript, React, HTML, CSS"
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS"
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090","React JS, JavaScript, React, HTML, CSS"
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma,"JavaScript, JSON, React"
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala,"JavaScript, React, HTML, Redux"
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ..."
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM,
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani,"React JS, JavaScript, JSON, React, HTML"
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi,"React JS, React"
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux"
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU,"React JS, JavaScript, React, HTML, CSS"
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD,"React JS, UI Development, JavaScript, React, H..."
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.,"HTML, CSS"
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish,"React JS, JavaScript, React, CSS, Redux"
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga,"JavaScript, React, HTML"
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK,"React JS, React, Redux"
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker"
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary,"Peoplesoft, HRMS, Application Designer, Integr..."
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR"
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des..."
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka,"Peoplesoft, Application Designer, Integration ..."
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des..."
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio..."
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des..."
44,Peoplesoft,Vinod Akkala ...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker"
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des..."
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des..."
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR"
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR"
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul,"Peoplesoft, PeopleTools, Application Designer,..."
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft,"Peoplesoft, Application Designer, Component In..."
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode"
52,Peoplesoft,\nR Ahmed ...,R,"Peoplesoft, PeopleTools, Application Designer,..."
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna,Peoplesoft
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata,"Peoplesoft, Application Designer"
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna,"Workday, HCM, Integration, Consultant, Busines..."
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name,"Workday, HCM, Integration, Consultant, Report ..."
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari,"Workday, HCM, Integration, Consultant, Busines..."
58,Work Day,Harikrishna Akula ...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu..."
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines..."
60,Work Day,\n ...,G,"Workday, HCM, Integration, Consultant"
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.,"Workday, HCM, Integration, Consultant, Busines..."
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI,"Workday, HCM, Consultant, Business Processes, ..."
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines..."
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence..."
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu,"Workday, HCM, Integration, Consultant, Busines..."
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA,"Workday, Consultant, Business Processes, Confi..."
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT,"Workday, HCM, Integration, Consultant"
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul,"Workday, HCM, Integration, Consultant, Busines..."
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh,"Workday, HCM, Consultant, Business Processes, ..."
70,Work Day,Shireesh Balasani ...,Shireesh,"Workday, HCM, Integration, Consultant, Busines..."
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday,"Workday, HCM, Integration, Consultant, Busines..."
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday,"Workday, HCM, Integration, Consultant, Busines..."
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines..."
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines..."
75,Work Day,...,Vinay,"Workday, HCM, Integration, Consultant, Busines..."

In [7]:
import nltk
from nltk.corpus import stopwords

STOPWORDS = set(stopwords.words('english'))

# Education Degrees
EDUCATION = ['BE','B.E.', 'B.E', 'BS','B.S','B.Com','BCA','ME','M.E', 
             'M.E.', 'M.S','B.com','10','10+2','BTECH', 'B.TECH', 'M.TECH', 
             'MTECH', 'SSC', 'HSC', 'C.B.S.E','CBSE','ICSE', 'X', 'XII','10th',
             '12th',' 10th',' 12th','Bachelor of Arts in Mathematics',
             'Master of Science in Analytics','Bachelor of Business Administration',
             'Major: Business Management']

def extract_education(text):
    nlp_text = nlp(text)
    nlp_text = [sent.text.strip() for sent in nlp_text.sents]
    edu = {}
    for index, t in enumerate(nlp_text):
        for tex in t.split():
            tex = re.sub(r'[?|$|.|!|,]', r'', tex)
            if tex in EDUCATION and tex not in STOPWORDS:
                edu[tex] = t + nlp_text[index + 1]

    education = []
    for key in edu.keys():
        year = re.search(re.compile(r'(((20|19)(\d{2})))'), edu[key])
        if year:
            education.append((key, ''.join(year[0])))
        else:
            education.append(key)
    return education

df['Education'] = df['Resume'].apply(extract_education)
df

,Category,Resume,Name,Skills,Education
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL,"SQL, ETL, Stored Procedures",[]
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[]
2,SQL Developer,BUDDHA VAMSI ...,IT,"SQL, ETL, Stored Procedures",[]
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA,"SQL, Stored Procedures, Database Management",[]
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad,"SQL, ETL, Stored Procedures",[10]
5,SQL Developer,\n Res...,Resume,"SQL, Stored Procedures","[(BE, 2013)]"
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL,"SQL, Stored Procedures, Query Optimization, Pe...","[(BCA, 2018)]"
7,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning",[]
8,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2019)]"
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2014)]"
10,SQL Developer,resume\n\n...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing",[]
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2018)]"
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2009)]"
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.,"SQL, ETL, Stored Procedures",[10]
14,React JS Developer,Name: Ravali P \n\n ...,Ravali,,[BE]
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN,"JavaScript, HTML, CSS",[]
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ...","[(10, 1997)]"
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS","[(SSC, 2012)]"
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H...",[]
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen,"MERN stack, HTML, CSS",[]
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE,"JavaScript, React, HTML, CSS",[]
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS",[10]
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090","React JS, JavaScript, React, HTML, CSS",[]
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma,"JavaScript, JSON, React",[]
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala,"JavaScript, React, HTML, Redux",[]
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ...",[]
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM,,[]
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani,"React JS, JavaScript, JSON, React, HTML",[]
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi,"React JS, React","[(SSC, 2018)]"
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux",[]
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU,"React JS, JavaScript, React, HTML, CSS",[]
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD,"React JS, UI Development, JavaScript, React, H...",[10]
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.,"HTML, CSS",[]
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish,"React JS, JavaScript, React, CSS, Redux",[]
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga,"JavaScript, React, HTML",[]
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK,"React JS, React, Redux",[]
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[]
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary,"Peoplesoft, HRMS, Application Designer, Integr...",[]
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR",[]
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des...",[]
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka,"Peoplesoft, Application Designer, Integration ...",[]
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des...","[12th, (10th, 2015), (10, 2008)]"
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio...",[]
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[]
44,Peoplesoft,Vinod Akkala ...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[]
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[]
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[]
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR",[BCA]
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR",[]
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul,"Peoplesoft, PeopleTools, Application Designer,...","[(10, 2019)]"
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft,"Peoplesoft, Application Designer, Component In...",[]
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode","[(10th, 1991)]"
52,Peoplesoft,\nR Ahmed ...,R,"Peoplesoft, PeopleTools, Application Designer,...",[]
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna,Peoplesoft,"[(BTECH, 2015), (SSC, 2009)]"
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata,"Peoplesoft, Application Designer","[(X, 2018)]"
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna,"Workday, HCM, Integration, Consultant, Busines...",[]
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name,"Workday, HCM, Integration, Consultant, Report ...",[]
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari,"Workday, HCM, Integration, Consultant, Busines...","[(10, 2012)]"
58,Work Day,Harikrishna Akula ...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu...",[]
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines...",[]
60,Work Day,\n ...,G,"Workday, HCM, Integration, Consultant",[]
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.,"Workday, HCM, Integration, Consultant, Busines...",[]
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI,"Workday, HCM, Consultant, Business Processes, ...",[]
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines...",[]
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence...",[]
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu,"Workday, HCM, Integration, Consultant, Busines...",[]
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA,"Workday, Consultant, Business Processes, Confi...",[]
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT,"Workday, HCM, Integration, Consultant",[]
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul,"Workday, HCM, Integration, Consultant, Busines...",[]
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh,"Workday, HCM, Consultant, Business Processes, ...",[]
70,Work Day,Shireesh Balasani ...,Shireesh,"Workday, HCM, Integration, Consultant, Busines...",[10]
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[]
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[]
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines...",[]
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines...",[]
75,Work Day,...,Vinay,"Workday, HCM, Integration, Consultant, Busines...",[]

In [8]:
def extract_date_of_birth(resume_text):
    # Define patterns for common date formats
    date_patterns = [
        r"\b(\d{1,2})[/.-](\d{1,2})[/.-](\d{4})\b",  # dd/mm/yyyy or dd-mm-yyyy or dd.mm.yyyy
        r"\b(\d{4})[/.-](\d{1,2})[/.-](\d{1,2})\b",  # yyyy/mm/dd or yyyy-mm-dd or yyyy.mm.dd
    ]

    # Iterate over the date patterns and search for a match in the resume text
    for pattern in date_patterns:
        match = re.search(pattern, resume_text)
        if match:
            # Return the matched date
            return match.group()

    return None

# Apply the extract_date_of_birth function to the "Resume" column
df['DOB'] = df['Resume'].apply(extract_date_of_birth)
df

,Category,Resume,Name,Skills,Education,DOB
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL,"SQL, ETL, Stored Procedures",[],None
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[],None
2,SQL Developer,BUDDHA VAMSI ...,IT,"SQL, ETL, Stored Procedures",[],22-08-1994
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA,"SQL, Stored Procedures, Database Management",[],None
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad,"SQL, ETL, Stored Procedures",[10],None
5,SQL Developer,\n Res...,Resume,"SQL, Stored Procedures","[(BE, 2013)]",None
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL,"SQL, Stored Procedures, Query Optimization, Pe...","[(BCA, 2018)]",None
7,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning",[],None
8,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2019)]",None
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2014)]",None
10,SQL Developer,resume\n\n...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing",[],None
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2018)]",None
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2009)]",None
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.,"SQL, ETL, Stored Procedures",[10],None
14,React JS Developer,Name: Ravali P \n\n ...,Ravali,,[BE],04/11/1995
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN,"JavaScript, HTML, CSS",[],None
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ...","[(10, 1997)]",None
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS","[(SSC, 2012)]",None
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H...",[],None
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen,"MERN stack, HTML, CSS",[],None
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE,"JavaScript, React, HTML, CSS",[],None
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS",[10],None
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090","React JS, JavaScript, React, HTML, CSS",[],None
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma,"JavaScript, JSON, React",[],None
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala,"JavaScript, React, HTML, Redux",[],None
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ...",[],None
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM,,[],None
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani,"React JS, JavaScript, JSON, React, HTML",[],None
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi,"React JS, React","[(SSC, 2018)]",None
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux",[],None
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU,"React JS, JavaScript, React, HTML, CSS",[],None
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD,"React JS, UI Development, JavaScript, React, H...",[10],1-06-1998
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.,"HTML, CSS",[],None
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish,"React JS, JavaScript, React, CSS, Redux",[],None
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga,"JavaScript, React, HTML",[],None
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK,"React JS, React, Redux",[],None
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary,"Peoplesoft, HRMS, Application Designer, Integr...",[],27/05/1987
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR",[],None
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka,"Peoplesoft, Application Designer, Integration ...",[],None
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des...","[12th, (10th, 2015), (10, 2008)]",None
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio...",[],None
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None
44,Peoplesoft,Vinod Akkala ...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR",[BCA],None
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR",[],None
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul,"Peoplesoft, PeopleTools, Application Designer,...","[(10, 2019)]",None
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft,"Peoplesoft, Application Designer, Component In...",[],None
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode","[(10th, 1991)]",None
52,Peoplesoft,\nR Ahmed ...,R,"Peoplesoft, PeopleTools, Application Designer,...",[],None
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna,Peoplesoft,"[(BTECH, 2015), (SSC, 2009)]",None
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata,"Peoplesoft, Application Designer","[(X, 2018)]",None
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna,"Workday, HCM, Integration, Consultant, Busines...",[],None
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name,"Workday, HCM, Integration, Consultant, Report ...",[],19-04-1993
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari,"Workday, HCM, Integration, Consultant, Busines...","[(10, 2012)]",None
58,Work Day,Harikrishna Akula ...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu...",[],None
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines...",[],None
60,Work Day,\n ...,G,"Workday, HCM, Integration, Consultant",[],None
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.,"Workday, HCM, Integration, Consultant, Busines...",[],None
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI,"Workday, HCM, Consultant, Business Processes, ...",[],None
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines...",[],None
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence...",[],15-02-1992
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu,"Workday, HCM, Integration, Consultant, Busines...",[],None
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA,"Workday, Consultant, Business Processes, Confi...",[],None
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT,"Workday, HCM, Integration, Consultant",[],None
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul,"Workday, HCM, Integration, Consultant, Busines...",[],None
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh,"Workday, HCM, Consultant, Business Processes, ...",[],None
70,Work Day,Shireesh Balasani ...,Shireesh,"Workday, HCM, Integration, Consultant, Busines...",[10],None
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines...",[],None
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines...",[],None
75,Work Day,...,Vinay,"Workday, HCM, Integration, Consultant, Busines...",[],None

In [9]:
def extract_experience(text):
    experience_pattern = r'\b(?!2012|100)(?:(?:0?\.\d+|\d+\.\d+)|[1-9]\d?(?:\.\d+)?)(?:\s*(?:years?|yrs?)\s*)?(?:\s*\d+(?:\.\d+)?\s*(?:months?|mos?)\s*)?(?:\s*(?:of\s)?experience)?'
    experience = re.search(experience_pattern, text, re.IGNORECASE)
    if experience:
        experience_value = re.findall(r'\d+(?:\.\d+)?', experience.group())
        # Exclude numbers greater than 26
        if float(experience_value[0]) <= 26:
            return experience_value[0]
    return ''

df['Experience_Years'] = df['Resume'].apply(extract_experience)
df

,Category,Resume,Name,Skills,Education,DOB,Experience_Years
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL,"SQL, ETL, Stored Procedures",[],None,2.4
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[],None,4
2,SQL Developer,BUDDHA VAMSI ...,IT,"SQL, ETL, Stored Procedures",[],22-08-1994,2.11
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA,"SQL, Stored Procedures, Database Management",[],None,2.8
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad,"SQL, ETL, Stored Procedures",[10],None,2.6
5,SQL Developer,\n Res...,Resume,"SQL, Stored Procedures","[(BE, 2013)]",None,3
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL,"SQL, Stored Procedures, Query Optimization, Pe...","[(BCA, 2018)]",None,20
7,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning",[],None,2.5
8,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2019)]",None,2.3
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2014)]",None,2.10
10,SQL Developer,resume\n\n...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing",[],None,2.5
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2018)]",None,3.5
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2009)]",None,3.2
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.,"SQL, ETL, Stored Procedures",[10],None,20
14,React JS Developer,Name: Ravali P \n\n ...,Ravali,,[BE],04/11/1995,20
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN,"JavaScript, HTML, CSS",[],None,20
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ...","[(10, 1997)]",None,4
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS","[(SSC, 2012)]",None,
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H...",[],None,
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen,"MERN stack, HTML, CSS",[],None,1
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE,"JavaScript, React, HTML, CSS",[],None,3
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS",[10],None,2
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090","React JS, JavaScript, React, HTML, CSS",[],None,20
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma,"JavaScript, JSON, React",[],None,2.8
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala,"JavaScript, React, HTML, Redux",[],None,2
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ...",[],None,3.2
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM,,[],None,
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani,"React JS, JavaScript, JSON, React, HTML",[],None,3.1
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi,"React JS, React","[(SSC, 2018)]",None,3
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux",[],None,1
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU,"React JS, JavaScript, React, HTML, CSS",[],None,2
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD,"React JS, UI Development, JavaScript, React, H...",[10],1-06-1998,20
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.,"HTML, CSS",[],None,2.4
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish,"React JS, JavaScript, React, CSS, Redux",[],None,1
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga,"JavaScript, React, HTML",[],None,1
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK,"React JS, React, Redux",[],None,2
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,20
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary,"Peoplesoft, HRMS, Application Designer, Integr...",[],27/05/1987,7
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR",[],None,4
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka,"Peoplesoft, Application Designer, Integration ...",[],None,
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des...","[12th, (10th, 2015), (10, 2008)]",None,6.8
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio...",[],None,10
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,4.2
44,Peoplesoft,Vinod Akkala ...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,7
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6.4
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,7.5
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR",[BCA],None,20
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR",[],None,4.1
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul,"Peoplesoft, PeopleTools, Application Designer,...","[(10, 2019)]",None,10.2
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft,"Peoplesoft, Application Designer, Component In...",[],None,4.6
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode","[(10th, 1991)]",None,3.6
52,Peoplesoft,\nR Ahmed ...,R,"Peoplesoft, PeopleTools, Application Designer,...",[],None,3.2
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna,Peoplesoft,"[(BTECH, 2015), (SSC, 2009)]",None,3.6
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata,"Peoplesoft, Application Designer","[(X, 2018)]",None,
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna,"Workday, HCM, Integration, Consultant, Busines...",[],None,19
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name,"Workday, HCM, Integration, Consultant, Report ...",[],19-04-1993,3
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari,"Workday, HCM, Integration, Consultant, Busines...","[(10, 2012)]",None,6.10
58,Work Day,Harikrishna Akula ...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu...",[],None,5.2
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines...",[],None,20
60,Work Day,\n ...,G,"Workday, HCM, Integration, Consultant",[],None,3
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.7
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI,"Workday, HCM, Consultant, Business Processes, ...",[],None,3
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines...",[],None,6
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence...",[],15-02-1992,5
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA,"Workday, Consultant, Business Processes, Confi...",[],None,3
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT,"Workday, HCM, Integration, Consultant",[],None,3.3
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul,"Workday, HCM, Integration, Consultant, Busines...",[],None,5
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh,"Workday, HCM, Consultant, Business Processes, ...",[],None,5
70,Work Day,Shireesh Balasani ...,Shireesh,"Workday, HCM, Integration, Consultant, Busines...",[10],None,10
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines...",[],None,6
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.3
75,Work Day,...,Vinay,"Workday, HCM, Integration, Consultant, Busines...",[],None,4.2

In [10]:
def extract_previous_work_experience(resume_text):
    # Define a pattern to extract previous work experience
    experience_pattern = r'(\d+(\.\d+)?\s*(?:years?|yrs?)\s*(?:of\s+experience)?)[\s-]*(.*)'

    # Search for the experience pattern in the resume text
    match = re.search(experience_pattern, resume_text, re.IGNORECASE)

    if match:
        return match.group(3).strip()  # Extract the third group (previous work experience)
    else:
        return 'Not Found'

# Apply the extract_previous_work_experience function to the "Resume" column
df['Work_Experience'] = df['Resume'].apply(extract_previous_work_experience)
df

,Category,Resume,Name,Skills,Education,DOB,Experience_Years,Work_Experience
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL,"SQL, ETL, Stored Procedures",[],None,2.4,in MS SQL Server (SSMS) and creating SSIS pack...
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[],None,4,of working experience in information technolog...
2,SQL Developer,BUDDHA VAMSI ...,IT,"SQL, ETL, Stored Procedures",[],22-08-1994,2.11,of IT experience as Database Engineer and curr...
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA,"SQL, Stored Procedures, Database Management",[],None,2.8,of Professional Software development experienc...
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad,"SQL, ETL, Stored Procedures",[10],None,2.6,Not Found
5,SQL Developer,\n Res...,Resume,"SQL, Stored Procedures","[(BE, 2013)]",None,3,6 Month of Experience on Oracle Developer.
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL,"SQL, Stored Procedures, Query Optimization, Pe...","[(BCA, 2018)]",None,20,"in Microsoft SQL Server environment, with thor..."
7,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning",[],None,2.5,of Total Experience in MICROSOFT SQL SERVER de...
8,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2019)]",None,2.3,Not Found
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2014)]",None,2.10,of Professional experience in SQL Server 2014/...
10,SQL Developer,resume\n\n...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing",[],None,2.5,of working experience in Microsoft SQLServer /...
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2018)]",None,3.5,"in system Design, Development and Support of M..."
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2009)]",None,3.2,of total experience in MICROSOFT SQL SERVER De...
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.,"SQL, ETL, Stored Procedures",[10],None,20,of IT Experience in Microsoft Business Intelli...
14,React JS Developer,Name: Ravali P \n\n ...,Ravali,,[BE],04/11/1995,20,Not Found
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN,"JavaScript, HTML, CSS",[],None,20,Not Found
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ...","[(10, 1997)]",None,4,from MetroLabs Services Pvt Ltd.
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS","[(SSC, 2012)]",None,,Not Found
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H...",[],None,,"in UI Development of Enterprise Applications, ..."
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen,"MERN stack, HTML, CSS",[],None,1,"of overall IT experience in Html, Sql, Reactjs..."
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE,"JavaScript, React, HTML, CSS",[],None,3,Not Found
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS",[10],None,2,"in UI development using Html5, CSS3, JavaScrip..."
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090","React JS, JavaScript, React, HTML, CSS",[],None,20,in developing UI-Applications. ◉ Proﬁcient and...
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma,"JavaScript, JSON, React",[],None,2.8,of IT experience as React Developer.
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala,"JavaScript, React, HTML, Redux",[],None,2,of successful IT experience in all phases of S...
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ...",[],None,3.2,of Extensive experience as a React JS/Web- Dev...
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM,,[],None,,Not Found
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani,"React JS, JavaScript, JSON, React, HTML",[],None,3.1,as a Software Engineer.
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi,"React JS, React","[(SSC, 2018)]",None,3,"Visakhapatnam, India"
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux",[],None,1,Not Found
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU,"React JS, JavaScript, React, HTML, CSS",[],None,2,"in software design, development, implementatio..."
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD,"React JS, UI Development, JavaScript, React, H...",[10],1-06-1998,20,Not Found
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.,"HTML, CSS",[],None,2.4,Not Found
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish,"React JS, JavaScript, React, CSS, Redux",[],None,1,& 2 months working as Jr. React Developer whic...
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga,"JavaScript, React, HTML",[],None,1,Not Found
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK,"React JS, React, Redux",[],None,2,’ Experience in Wipro
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,20,Not Found
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary,"Peoplesoft, HRMS, Application Designer, Integr...",[],27/05/1987,7,Not Found
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR",[],None,4,Not Found
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6,working in PeopleSoft Administration and perfo...
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka,"Peoplesoft, Application Designer, Integration ...",[],None,,(September 2016 - present) of experience as Pe...
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des...","[12th, (10th, 2015), (10, 2008)]",None,6.8,’ experience as PeopleSoft Administrator. Inst...
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio...",[],None,10,Not Found
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,4.2,’ Experience in PeopleSoft Admin and PeopleSof...
44,Peoplesoft,Vinod Akkala ...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,7,Not Found
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6.4,Experience in IT. With my valid expertise of 4...
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,7.5,"in PeopleSoft, I hope to enhance my skill set ..."
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR",[BCA],None,20,"08 Months in multiple PeopleSoft Upgrade, Impl..."
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR",[],None,4.1,"Experience of Development, Support and mainten..."
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul,"Peoplesoft, PeopleTools, Application Designer,...","[(10, 2019)]",None,10.2,in PeopleSoft as a Technical Consultant.
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft,"Peoplesoft, Application Designer, Component In...",[],None,4.6,"in PeopleSoft application enhancement, impleme..."
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode","[(10th, 1991)]",None,3.6,in Financial Supply Chain Management and proce...
52,Peoplesoft,\nR Ahmed ...,R,"Peoplesoft, PeopleTools, Application Designer,...",[],None,3.2,as PeopleSoft Consultant.
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna,Peoplesoft,"[(BTECH, 2015), (SSC, 2009)]",None,3.6,in IT. Extended expertise in PeopleSoft Financ...
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata,"Peoplesoft, Application Designer","[(X, 2018)]",None,,in assistance and development for projects lik...
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna,"Workday, HCM, Integration, Consultant, Busines...",[],None,19,of IT experience in developing and Implementat...
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name,"Workday, HCM, Integration, Consultant, Report ...",[],19-04-1993,3,Not Found
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari,"Workday, HCM, Integration, Consultant, Busines...","[(10, 2012)]",None,6.10,. of experience in Software Engineering with 3...
58,Work Day,Harikrishna Akula ...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu...",[],None,5.2,"of IT experience, around 3.8 years of experien..."
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines...",[],None,20,Not Found
60,Work Day,\n ...,G,"Workday, HCM, Integration, Consultant",[],None,3,of IT ERP experience which include 2+ years as...
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.7,in Information Technology with 3.10 years of e...
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI,"Workday, HCM, Consultant, Business Processes, ...",[],None,3,in Workday as Functional HCM Consultant.
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,of IT experience in developing and Implementat...
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence...",[],15-02-1992,5,Not Found
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,Not Found
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA,"Workday, Consultant, Business Processes, Confi...",[],None,3,of IT experience as a Workday Consultant.
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT,"Workday, HCM, Integration, Consultant",[],None,3.3,of IT experience as Workday HCM Technical Cons...
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,"in workday HCM and Expertise in Workday HCM , ..."
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh,"Workday, HCM, Consultant, Business Processes, ...",[],None,5,Not Found
70,Work Day,Shireesh Balasani ...,Shireesh,"Workday, HCM, Integration, Consultant, Busines...",[10],None,10,.
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,as Workday Consultant and good experience on R...
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,"in workday HCM, completed Workday Integration ..."
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,Not Found
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.3,in IT in which 3+ years of experience in imple...
75,Work Day,...,Vinay,"Workday, HCM, Integration, Consultant, Busines...",[],None,4.2,of Total Experience in as a Workday Functiona...

In [11]:
def extract_phone_number(text):
    phone_pattern = r'(\+91)?\d{10}'
    phone = re.search(phone_pattern, text)
    if phone:
        return phone.group()
    else:
        return '-'

df['Phone'] = df['Resume'].apply(extract_phone_number)
df

,Category,Resume,Name,Skills,Education,DOB,Experience_Years,Work_Experience,Phone
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL,"SQL, ETL, Stored Procedures",[],None,2.4,in MS SQL Server (SSMS) and creating SSIS pack...,-
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[],None,4,of working experience in information technolog...,-
2,SQL Developer,BUDDHA VAMSI ...,IT,"SQL, ETL, Stored Procedures",[],22-08-1994,2.11,of IT experience as Database Engineer and curr...,-
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA,"SQL, Stored Procedures, Database Management",[],None,2.8,of Professional Software development experienc...,-
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad,"SQL, ETL, Stored Procedures",[10],None,2.6,Not Found,-
5,SQL Developer,\n Res...,Resume,"SQL, Stored Procedures","[(BE, 2013)]",None,3,6 Month of Experience on Oracle Developer.,-
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL,"SQL, Stored Procedures, Query Optimization, Pe...","[(BCA, 2018)]",None,20,"in Microsoft SQL Server environment, with thor...",-
7,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning",[],None,2.5,of Total Experience in MICROSOFT SQL SERVER de...,-
8,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2019)]",None,2.3,Not Found,-
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2014)]",None,2.10,of Professional experience in SQL Server 2014/...,-
10,SQL Developer,resume\n\n...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing",[],None,2.5,of working experience in Microsoft SQLServer /...,-
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2018)]",None,3.5,"in system Design, Development and Support of M...",-
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2009)]",None,3.2,of total experience in MICROSOFT SQL SERVER De...,-
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.,"SQL, ETL, Stored Procedures",[10],None,20,of IT Experience in Microsoft Business Intelli...,-
14,React JS Developer,Name: Ravali P \n\n ...,Ravali,,[BE],04/11/1995,20,Not Found,-
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN,"JavaScript, HTML, CSS",[],None,20,Not Found,-
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ...","[(10, 1997)]",None,4,from MetroLabs Services Pvt Ltd.,-
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS","[(SSC, 2012)]",None,,Not Found,9908576950
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H...",[],None,,"in UI Development of Enterprise Applications, ...",-
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen,"MERN stack, HTML, CSS",[],None,1,"of overall IT experience in Html, Sql, Reactjs...",-
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE,"JavaScript, React, HTML, CSS",[],None,3,Not Found,-
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS",[10],None,2,"in UI development using Html5, CSS3, JavaScrip...",-
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090","React JS, JavaScript, React, HTML, CSS",[],None,20,in developing UI-Applications. ◉ Proﬁcient and...,-
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma,"JavaScript, JSON, React",[],None,2.8,of IT experience as React Developer.,-
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala,"JavaScript, React, HTML, Redux",[],None,2,of successful IT experience in all phases of S...,-
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ...",[],None,3.2,of Extensive experience as a React JS/Web- Dev...,-
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM,,[],None,,Not Found,-
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani,"React JS, JavaScript, JSON, React, HTML",[],None,3.1,as a Software Engineer.,-
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi,"React JS, React","[(SSC, 2018)]",None,3,"Visakhapatnam, India",-
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux",[],None,1,Not Found,-
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU,"React JS, JavaScript, React, HTML, CSS",[],None,2,"in software design, development, implementatio...",-
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD,"React JS, UI Development, JavaScript, React, H...",[10],1-06-1998,20,Not Found,-
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.,"HTML, CSS",[],None,2.4,Not Found,-
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish,"React JS, JavaScript, React, CSS, Redux",[],None,1,& 2 months working as Jr. React Developer whic...,-
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga,"JavaScript, React, HTML",[],None,1,Not Found,-
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK,"React JS, React, Redux",[],None,2,’ Experience in Wipro,-
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,20,Not Found,-
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary,"Peoplesoft, HRMS, Application Designer, Integr...",[],27/05/1987,7,Not Found,-
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR",[],None,4,Not Found,-
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6,working in PeopleSoft Administration and perfo...,-
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka,"Peoplesoft, Application Designer, Integration ...",[],None,,(September 2016 - present) of experience as Pe...,-
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des...","[12th, (10th, 2015), (10, 2008)]",None,6.8,’ experience as PeopleSoft Administrator. Inst...,-
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio...",[],None,10,Not Found,-
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,4.2,’ Experience in PeopleSoft Admin and PeopleSof...,-
44,Peoplesoft,Vinod Akkala ...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,7,Not Found,-
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6.4,Experience in IT. With my valid expertise of 4...,-
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,7.5,"in PeopleSoft, I hope to enhance my skill set ...",-
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR",[BCA],None,20,"08 Months in multiple PeopleSoft Upgrade, Impl...",-
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR",[],None,4.1,"Experience of Development, Support and mainten...",-
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul,"Peoplesoft, PeopleTools, Application Designer,...","[(10, 2019)]",None,10.2,in PeopleSoft as a Technical Consultant.,-
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft,"Peoplesoft, Application Designer, Component In...",[],None,4.6,"in PeopleSoft application enhancement, impleme...",-
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode","[(10th, 1991)]",None,3.6,in Financial Supply Chain Management and proce...,-
52,Peoplesoft,\nR Ahmed ...,R,"Peoplesoft, PeopleTools, Application Designer,...",[],None,3.2,as PeopleSoft Consultant.,-
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna,Peoplesoft,"[(BTECH, 2015), (SSC, 2009)]",None,3.6,in IT. Extended expertise in PeopleSoft Financ...,-
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata,"Peoplesoft, Application Designer","[(X, 2018)]",None,,in assistance and development for projects lik...,-
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna,"Workday, HCM, Integration, Consultant, Busines...",[],None,19,of IT experience in developing and Implementat...,-
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name,"Workday, HCM, Integration, Consultant, Report ...",[],19-04-1993,3,Not Found,-
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari,"Workday, HCM, Integration, Consultant, Busines...","[(10, 2012)]",None,6.10,. of experience in Software Engineering with 3...,-
58,Work Day,Harikrishna Akula ...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu...",[],None,5.2,"of IT experience, around 3.8 years of experien...",-
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines...",[],None,20,Not Found,-
60,Work Day,\n ...,G,"Workday, HCM, Integration, Consultant",[],None,3,of IT ERP experience which include 2+ years as...,-
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.7,in Information Technology with 3.10 years of e...,-
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI,"Workday, HCM, Consultant, Business Processes, ...",[],None,3,in Workday as Functional HCM Consultant.,-
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,of IT experience in developing and Implementat...,-
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence...",[],15-02-1992,5,Not Found,-
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,Not Found,-
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA,"Workday, Consultant, Business Processes, Confi...",[],None,3,of IT experience as a Workday Consultant.,-
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT,"Workday, HCM, Integration, Consultant",[],None,3.3,of IT experience as Workday HCM Technical Cons...,-
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,"in workday HCM and Expertise in Workday HCM , ...",-
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh,"Workday, HCM, Consultant, Business Processes, ...",[],None,5,Not Found,-
70,Work Day,Shireesh Balasani ...,Shireesh,"Workday, HCM, Integration, Consultant, Busines...",[10],None,10,.,-
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,as Workday Consultant and good experience on R...,-
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,"in workday HCM, completed Workday Integration ...",-
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,Not Found,-
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.3,in IT in which 3+ years of experience in imple...,-
75,Work Day,...,Vinay,"Workday, HCM, Integration, Consultant, Busines...",[],None,4.2,of Total Experience in as a Workday Functiona...,-

In [12]:
def extract_email(text):
    email_pattern = r'\b[A-Za-z0-9._%+-]+@(?:[A-Za-z0-9-]+\.)+[A-Za-z]{2,}\b'
    email = re.search(email_pattern, text)
    if email:
        return email.group()
    else:
        return '-'

df['Email_ID'] = df['Resume'].apply(extract_email)
df

,Category,Resume,Name,Skills,Education,DOB,Experience_Years,Work_Experience,Phone,Email_ID
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL,"SQL, ETL, Stored Procedures",[],None,2.4,in MS SQL Server (SSMS) and creating SSIS pack...,-,-
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[],None,4,of working experience in information technolog...,-,-
2,SQL Developer,BUDDHA VAMSI ...,IT,"SQL, ETL, Stored Procedures",[],22-08-1994,2.11,of IT experience as Database Engineer and curr...,-,-
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA,"SQL, Stored Procedures, Database Management",[],None,2.8,of Professional Software development experienc...,-,-
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad,"SQL, ETL, Stored Procedures",[10],None,2.6,Not Found,-,-
5,SQL Developer,\n Res...,Resume,"SQL, Stored Procedures","[(BE, 2013)]",None,3,6 Month of Experience on Oracle Developer.,-,-
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL,"SQL, Stored Procedures, Query Optimization, Pe...","[(BCA, 2018)]",None,20,"in Microsoft SQL Server environment, with thor...",-,-
7,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning",[],None,2.5,of Total Experience in MICROSOFT SQL SERVER de...,-,-
8,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2019)]",None,2.3,Not Found,-,-
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2014)]",None,2.10,of Professional experience in SQL Server 2014/...,-,-
10,SQL Developer,resume\n\n...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing",[],None,2.5,of working experience in Microsoft SQLServer /...,-,-
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2018)]",None,3.5,"in system Design, Development and Support of M...",-,-
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2009)]",None,3.2,of total experience in MICROSOFT SQL SERVER De...,-,-
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.,"SQL, ETL, Stored Procedures",[10],None,20,of IT Experience in Microsoft Business Intelli...,-,-
14,React JS Developer,Name: Ravali P \n\n ...,Ravali,,[BE],04/11/1995,20,Not Found,-,-
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN,"JavaScript, HTML, CSS",[],None,20,Not Found,-,-
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ...","[(10, 1997)]",None,4,from MetroLabs Services Pvt Ltd.,-,-
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS","[(SSC, 2012)]",None,,Not Found,9908576950,haripriyabattini@gmai.com
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H...",[],None,,"in UI Development of Enterprise Applications, ...",-,-
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen,"MERN stack, HTML, CSS",[],None,1,"of overall IT experience in Html, Sql, Reactjs...",-,-
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE,"JavaScript, React, HTML, CSS",[],None,3,Not Found,-,-
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS",[10],None,2,"in UI development using Html5, CSS3, JavaScrip...",-,-
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090","React JS, JavaScript, React, HTML, CSS",[],None,20,in developing UI-Applications. ◉ Proﬁcient and...,-,-
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma,"JavaScript, JSON, React",[],None,2.8,of IT experience as React Developer.,-,-
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala,"JavaScript, React, HTML, Redux",[],None,2,of successful IT experience in all phases of S...,-,-
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ...",[],None,3.2,of Extensive experience as a React JS/Web- Dev...,-,-
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM,,[],None,,Not Found,-,-
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani,"React JS, JavaScript, JSON, React, HTML",[],None,3.1,as a Software Engineer.,-,-
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi,"React JS, React","[(SSC, 2018)]",None,3,"Visakhapatnam, India",-,-
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux",[],None,1,Not Found,-,-
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU,"React JS, JavaScript, React, HTML, CSS",[],None,2,"in software design, development, implementatio...",-,-
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD,"React JS, UI Development, JavaScript, React, H...",[10],1-06-1998,20,Not Found,-,-
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.,"HTML, CSS",[],None,2.4,Not Found,-,-
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish,"React JS, JavaScript, React, CSS, Redux",[],None,1,& 2 months working as Jr. React Developer whic...,-,-
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga,"JavaScript, React, HTML",[],None,1,Not Found,-,-
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK,"React JS, React, Redux",[],None,2,’ Experience in Wipro,-,sharukabdul786@gmail.com
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,20,Not Found,-,-
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary,"Peoplesoft, HRMS, Application Designer, Integr...",[],27/05/1987,7,Not Found,-,-
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR",[],None,4,Not Found,-,-
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6,working in PeopleSoft Administration and perfo...,-,-
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka,"Peoplesoft, Application Designer, Integration ...",[],None,,(September 2016 - present) of experience as Pe...,-,-
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des...","[12th, (10th, 2015), (10, 2008)]",None,6.8,’ experience as PeopleSoft Administrator. Inst...,-,-
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio...",[],None,10,Not Found,-,-
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,4.2,’ Experience in PeopleSoft Admin and PeopleSof...,-,-
44,Peoplesoft,Vinod Akkala ...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,7,Not Found,-,-
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6.4,Experience in IT. With my valid expertise of 4...,-,-
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,7.5,"in PeopleSoft, I hope to enhance my skill set ...",-,-
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR",[BCA],None,20,"08 Months in multiple PeopleSoft Upgrade, Impl...",-,-
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR",[],None,4.1,"Experience of Development, Support and mainten...",-,-
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul,"Peoplesoft, PeopleTools, Application Designer,...","[(10, 2019)]",None,10.2,in PeopleSoft as a Technical Consultant.,-,-
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft,"Peoplesoft, Application Designer, Component In...",[],None,4.6,"in PeopleSoft application enhancement, impleme...",-,-
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode","[(10th, 1991)]",None,3.6,in Financial Supply Chain Management and proce...,-,-
52,Peoplesoft,\nR Ahmed ...,R,"Peoplesoft, PeopleTools, Application Designer,...",[],None,3.2,as PeopleSoft Consultant.,-,-
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna,Peoplesoft,"[(BTECH, 2015), (SSC, 2009)]",None,3.6,in IT. Extended expertise in PeopleSoft Financ...,-,-
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata,"Peoplesoft, Application Designer","[(X, 2018)]",None,,in assistance and development for projects lik...,-,-
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna,"Workday, HCM, Integration, Consultant, Busines...",[],None,19,of IT experience in developing and Implementat...,-,-
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name,"Workday, HCM, Integration, Consultant, Report ...",[],19-04-1993,3,Not Found,-,-
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari,"Workday, HCM, Integration, Consultant, Busines...","[(10, 2012)]",None,6.10,. of experience in Software Engineering with 3...,-,-
58,Work Day,Harikrishna Akula ...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu...",[],None,5.2,"of IT experience, around 3.8 years of experien...",-,-
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines...",[],None,20,Not Found,-,-
60,Work Day,\n ...,G,"Workday, HCM, Integration, Consultant",[],None,3,of IT ERP experience which include 2+ years as...,-,-
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.7,in Information Technology with 3.10 years of e...,-,-
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI,"Workday, HCM, Consultant, Business Processes, ...",[],None,3,in Workday as Functional HCM Consultant.,-,-
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,of IT experience in developing and Implementat...,-,-
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence...",[],15-02-1992,5,Not Found,-,-
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,Not Found,-,-
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA,"Workday, Consultant, Business Processes, Confi...",[],None,3,of IT experience as a Workday Consultant.,-,-
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT,"Workday, HCM, Integration, Consultant",[],None,3.3,of IT experience as Workday HCM Technical Cons...,-,-
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,"in workday HCM and Expertise in Workday HCM , ...",-,-
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh,"Workday, HCM, Consultant, Business Processes, ...",[],None,5,Not Found,-,-
70,Work Day,Shireesh Balasani ...,Shireesh,"Workday, HCM, Integration, Consultant, Busines...",[10],None,10,.,-,-
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,as Workday Consultant and good experience on R...,-,-
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,"in workday HCM, completed Workday Integration ...",-,-
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,Not Found,-,-
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.3,in IT in which 3+ years of experience in imple...,-,-
75,Work Day,...,Vinay,"Workday, HCM, Integration, Consultant, Busines...",[],None,4.2,of Total Experience in as a Workday Functiona...,-,-

In [13]:
def extract_links(resume_text):
    link_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
    links = re.findall(link_pattern, resume_text)
    if links:
        return links
    else:
        return '-'

# Apply the extract_links function to the "Resume" column
df['Links'] = df['Resume'].apply(extract_links)
df

,Category,Resume,Name,Skills,Education,DOB,Experience_Years,Work_Experience,Phone,Email_ID,Links
0,SQL Developer,ANIL KUMAR MADDUKURI \t\t\nSQL & MSBI Develop...,ANIL,"SQL, ETL, Stored Procedures",[],None,2.4,in MS SQL Server (SSMS) and creating SSIS pack...,-,-,-
1,SQL Developer,\nAradhana Tripathi\n\nCurrent Location: Gachi...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[],None,4,of working experience in information technolog...,-,-,-
2,SQL Developer,BUDDHA VAMSI ...,IT,"SQL, ETL, Stored Procedures",[],22-08-1994,2.11,of IT experience as Database Engineer and curr...,-,-,-
3,SQL Developer,KAMBALLA PRADEEP ...,KAMBALLA,"SQL, Stored Procedures, Database Management",[],None,2.8,of Professional Software development experienc...,-,-,-
4,SQL Developer,\n\n\n Hyderabad\n\nNazeer Basha\nSQL and Pow...,Hyderabad,"SQL, ETL, Stored Procedures",[10],None,2.6,Not Found,-,-,-
5,SQL Developer,\n Res...,Resume,"SQL, Stored Procedures","[(BE, 2013)]",None,3,6 Month of Experience on Oracle Developer.,-,-,-
6,SQL Developer,SQL DEVELOPER\nName: - Bandi prem sai\n\n\nW...,SQL,"SQL, Stored Procedures, Query Optimization, Pe...","[(BCA, 2018)]",None,20,"in Microsoft SQL Server environment, with thor...",-,-,-
7,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning",[],None,2.5,of Total Experience in MICROSOFT SQL SERVER de...,-,-,-
8,SQL Developer,SQL SER...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2019)]",None,2.3,Not Found,-,-,-
9,SQL Developer,RAJU PAVANA KUMARI\n\n\nProfessional Summary:...,RAJU,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2014)]",None,2.10,of Professional experience in SQL Server 2014/...,-,-,-
10,SQL Developer,resume\n\n...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing",[],None,2.5,of working experience in Microsoft SQLServer /...,-,-,-
11,SQL Developer,Name: Ramesh\n\nCareer Objective: \n ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2018)]",None,3.5,"in system Design, Development and Support of M...",-,-,-
12,SQL Developer,Career objective\n\t\nA rewarding opportunity ...,Experience,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2009)]",None,3.2,of total experience in MICROSOFT SQL SERVER De...,-,-,-
13,SQL Developer,B. vinod kumar\n\nOBJECTIVE:\nWilling to work ...,B.,"SQL, ETL, Stored Procedures",[10],None,20,of IT Experience in Microsoft Business Intelli...,-,-,-
14,React JS Developer,Name: Ravali P \n\n ...,Ravali,,[BE],04/11/1995,20,Not Found,-,-,-
15,React JS Developer,\nName:SUSOVAN BAG \nSeeking a challeng...,SUSOVAN,"JavaScript, HTML, CSS",[],None,20,Not Found,-,-,-
16,React JS Developer,Kanumuru Deepak Reddy\n\n\n\nCAREER OBJECTIVE:...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ...","[(10, 1997)]",None,4,from MetroLabs Services Pvt Ltd.,-,-,-
17,React JS Developer,HARIPRIYA BATTINA \nExperience as UI Developer...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS","[(SSC, 2012)]",None,,Not Found,9908576950,haripriyabattini@gmai.com,-
18,React JS Developer,KAMALAKAR REDDY. A \nLinked In: https://www.li...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H...",[],None,,"in UI Development of Enterprise Applications, ...",-,-,[https://www.linkedin.com/in/kamalakar-reddy-7...
19,React JS Developer,\nNaveen Sadhu\n\n\nTitle: software developer\...,Naveen,"MERN stack, HTML, CSS",[],None,1,"of overall IT experience in Html, Sql, Reactjs...",-,-,-
20,React JS Developer,\n\n\nPROFILE\nSearching for the opportunity t...,PROFILE,"JavaScript, React, HTML, CSS",[],None,3,Not Found,-,-,-
21,React JS Developer,\nPRAGNYA PATTNAIK\n \n \n \n Expertise: \n \...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS",[10],None,2,"in UI development using Html5, CSS3, JavaScrip...",-,-,-
22,React JS Developer,"\n\n 204,Sri geethika prestige,road number 10...","Hyderabad,500090","React JS, JavaScript, React, HTML, CSS",[],None,20,in developing UI-Applications. ◉ Proﬁcient and...,-,-,-
23,React JS Developer,\n\nThirupathamma Balla\n\nSUMMARY:\n\n2.8 yea...,Thirupathamma,"JavaScript, JSON, React",[],None,2.8,of IT experience as React Developer.,-,-,-
24,React JS Developer,Maryala Vinay Reddy\n\nProfessional Summary:\t...,Maryala,"JavaScript, React, HTML, Redux",[],None,2,of successful IT experience in all phases of S...,-,-,-
25,React JS Developer,\nUi-Developer/ React JS Developer \nNAME: KRI...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ...",[],None,3.2,of Extensive experience as a React JS/Web- Dev...,-,-,-
26,React JS Developer,CURRICULUM VITAE\n\n\n\n\nI hereby declare tha...,CURRICULUM,,[],None,,Not Found,-,-,-
27,React JS Developer,Kotani Durga Prasad\n\n\nObjective:\n\nAspiran...,Kotani,"React JS, JavaScript, JSON, React, HTML",[],None,3.1,as a Software Engineer.,-,-,-
28,React JS Developer,Venkatalakshmi Pedireddy\nSoftware Developer\n...,Venkatalakshmi,"React JS, React","[(SSC, 2018)]",None,3,"Visakhapatnam, India",-,-,[https://batvidcoronaawareness.000webhostapp.com]
29,React JS Developer,KAMBALA SAI SURENDRA \n \n\tMandepeta \t \n ...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux",[],None,1,Not Found,-,-,-
30,React JS Developer,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,MAREEDU,"React JS, JavaScript, React, HTML, CSS",[],None,2,"in software design, development, implementatio...",-,-,-
31,React JS Developer,MD KHIZARUDDIN RAUF \n \t EXPERIENCE \n \n...,MD,"React JS, UI Development, JavaScript, React, H...",[10],1-06-1998,20,Not Found,-,-,-
32,React JS Developer,\nName: M. Prabakaran \nTitle: UI Developer\nP...,M.,"HTML, CSS",[],None,2.4,Not Found,-,-,-
33,React JS Developer,\nPranish Sonone\n\t\n\n\n\n\nCareer summary:\...,Pranish,"React JS, JavaScript, React, CSS, Redux",[],None,1,& 2 months working as Jr. React Developer whic...,-,-,-
34,React JS Developer,Ranga Gaganam \n \n \nHaving 1+ years of succ...,Ranga,"JavaScript, React, HTML",[],None,1,Not Found,-,-,-
35,React JS Developer,SHAIK ABDUL SHARUK \n2 years’ Experience in ...,SHAIK,"React JS, React, Redux",[],None,2,’ Experience in Wipro,-,sharukabdul786@gmail.com,[https://github.com/sharukabdul/Todo-List]
36,Peoplesoft,Anubhav Kumar Singh\t\t\n\n To work in a gl...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,20,Not Found,-,-,-
37,Peoplesoft,\n\n\n\n\n\n\t\n\nProfile Summary:\t\t\t\t\t\t...,Summary,"Peoplesoft, HRMS, Application Designer, Integr...",[],27/05/1987,7,Not Found,-,-,-
38,Peoplesoft,PeopleSoft Database Administrator\n ...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR",[],None,4,Not Found,-,-,-
39,Peoplesoft,Murali\n\nExperience Summary \n\nI have 6 year...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6,working in PeopleSoft Administration and perfo...,-,-,-
40,Peoplesoft,"Priyanka Ramadoss\n61/46, MountPleasant, \nCoo...",Priyanka,"Peoplesoft, Application Designer, Integration ...",[],None,,(September 2016 - present) of experience as Pe...,-,-,-
41,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUMMARY\n\...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des...","[12th, (10th, 2015), (10, 2008)]",None,6.8,’ experience as PeopleSoft Administrator. Inst...,-,-,-
42,Peoplesoft,PEOPLESOFT Administrator\n\n\nSRINIVAS.K \t\t\...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio...",[],None,10,Not Found,-,-,-
43,Peoplesoft,PeopleSoft Admin\nVARKALA VIKAS\n\nCareer Obj...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,4.2,’ Experience in PeopleSoft Admin and PeopleSof...,-,-,-
44,Peoplesoft,Vinod Akkala ...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,7,Not Found,-,-,-
45,Peoplesoft,PeopleSoft Admin/PeopleSoft DBA\n\nGanesh All...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6.4,Experience in IT. With my valid expertise of 4...,-,-,-
46,Peoplesoft,PeopleSoft Administration\n \nVivekanand Sayan...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,7.5,"in PeopleSoft, I hope to enhance my skill set ...",-,-,-
47,Peoplesoft,Arun Venu\n\n EXPERIENCE SUMMARY\t\n\nExperie...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR",[BCA],None,20,"08 Months in multiple PeopleSoft Upgrade, Impl...",-,-,-
48,Peoplesoft,\n\n\n\n\nExperience Summary\n4.1 years- Exper...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR",[],None,4.1,"Experience of Development, Support and mainten...",-,-,-
49,Peoplesoft,Rahul Ahuja\n---------------------------------...,Rahul,"Peoplesoft, PeopleTools, Application Designer,...","[(10, 2019)]",None,10.2,in PeopleSoft as a Technical Consultant.,-,-,-
50,Peoplesoft,\nHaving 4.6 years of experience in PeopleSoft...,PeopleSoft,"Peoplesoft, Application Designer, Component In...",[],None,4.6,"in PeopleSoft application enhancement, impleme...",-,-,-
51,Peoplesoft,\n\nCAREER OBJECTIVE\t\t\n\nPursuing Peopleso...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode","[(10th, 1991)]",None,3.6,in Financial Supply Chain Management and proce...,-,-,-
52,Peoplesoft,\nR Ahmed ...,R,"Peoplesoft, PeopleTools, Application Designer,...",[],None,3.2,as PeopleSoft Consultant.,-,-,-
53,Peoplesoft,Tanna Sujatha \n\n\n\nOBJECTIVE\nSeeking a cha...,Tanna,Peoplesoft,"[(BTECH, 2015), (SSC, 2009)]",None,3.6,in IT. Extended expertise in PeopleSoft Financ...,-,-,-
54,Peoplesoft,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nC O N ...,Manyata,"Peoplesoft, Application Designer","[(X, 2018)]",None,,in assistance and development for projects lik...,-,-,-
55,Work Day,Chinna Subbarayudu M\nDOB: 06th March 1994\nNa...,Chinna,"Workday, HCM, Integration, Consultant, Busines...",[],None,19,of IT experience in developing and Implementat...,-,-,-
56,Work Day,\t\n\n\nName : Gopi Krishna Reddy\n\t\...,Name,"Workday, HCM, Integration, Consultant, Report ...",[],19-04-1993,3,Not Found,-,-,-
57,Work Day,Hari Krishna M\n\n\nSummary:\nA result oriente...,Hari,"Workday, HCM, Integration, Consultant, Busines...","[(10, 2012)]",None,6.10,. of experience in Software Engineering with 3...,-,-,-
58,Work Day,Harikrishna Akula ...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu...",[],None,5.2,"of IT experience, around 3.8 years of experien...",-,-,-
59,Work Day,HIMA.MENDU\n \n\nCareer Objective\nTo continu...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines...",[],None,20,Not Found,-,-,-
60,Work Day,\n ...,G,"Workday, HCM, Integration, Consultant",[],None,3,of IT ERP experience which include 2+ years as...,-,-,-
61,Work Day,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\n\t\nPR...,J.,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.7,in Information Technology with 3.10 years of e...,-,-,-
62,Work Day,\n\nJYOTI VERMA\t\t\t\t\t\n\n\n\n3 years of Ex...,JYOTI,"Workday, HCM, Consultant, Business Processes, ...",[],None,3,in Workday as Functional HCM Consultant.,-,-,-
63,Work Day,\t\t\t\t\tMadeeswar A\n\t\n\t\nPROFILE SUMMARY...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,of IT experience in developing and Implementat...,-,-,-
64,Work Day,\n\nMooraboyina Guravaiah\nWorkday Integration...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence...",[],15-02-1992,5,Not Found,-,-,-
65,Work Day,Name\t: Naresh Babu Cherukuri\n\nObjective:\nT...,Babu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,Not Found,-,-,-
66,Work Day,VENKATA SAIKRISHNA\n Workday Consultant\n\n\nP...,VENKATA,"Workday, Consultant, Business Processes, Confi...",[],None,3,of IT experience as a Workday Consultant.,-,-,-
67,Work Day,\n\n\n3.3 years of IT experience as Workday HC...,IT,"Workday, HCM, Integration, Consultant",[],None,3.3,of IT experience as Workday HCM Technical Cons...,-,-,-
68,Work Day,Rahul (Techno Functional Consultant) \nProfe...,Rahul,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,"in workday HCM and Expertise in Workday HCM , ...",-,-,-
69,Work Day,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,Ramesh,"Workday, HCM, Consultant, Business Processes, ...",[],None,5,Not Found,-,-,-
70,Work Day,Shireesh Balasani ...,Shireesh,"Workday, HCM, Integration, Consultant, Busines...",[10],None,10,.,-,-,-
71,Work Day,\tWorkday Integration Consultant\n\nName ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,as Workday Consultant and good experience on R...,-,-,-
72,Work Day,Seeking suitable positions in Workday HCM as ...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,"in workday HCM, completed Workday Integration ...",-,-,-
73,Work Day,\nWORKDAY | HCM | FCM\nName \t\t: Kumar S.S\nR...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,Not Found,-,-,-
74,Work Day,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.3,in IT in which 3+ years of experience in imple...,-,-,-
75,Work Day,...,Vinay,"Workday, HCM, Integration, Consultant, Busines...",[],None,4.2,of Total Experience in as a Workday Functiona...,-,-,-

In [14]:
def clean_resume_data(resume_text):
    resume_text = re.sub('http\S+\s*', ' ', resume_text)  # remove URLs
    resume_text = re.sub('#\S+', '', resume_text)  # remove hashtags
    resume_text = re.sub('@\S+', ' ', resume_text)  # remove mentions
    resume_text = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', resume_text)  # remove punctuations
    resume_text = re.sub(r'[^\x00-\x7f]', ' ', resume_text) 
    resume_text = re.sub('\s+', ' ', resume_text)  # remove extra whitespace
    return resume_text

df['Resume'] = df['Resume'].apply(clean_resume_data)
df

,Category,Resume,Name,Skills,Education,DOB,Experience_Years,Work_Experience,Phone,Email_ID,Links
0,SQL Developer,ANIL KUMAR MADDUKURI SQL MSBI Developer Summar...,ANIL,"SQL, ETL, Stored Procedures",[],None,2.4,in MS SQL Server (SSMS) and creating SSIS pack...,-,-,-
1,SQL Developer,Aradhana Tripathi Current Location Gachibowli...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[],None,4,of working experience in information technolog...,-,-,-
2,SQL Developer,BUDDHA VAMSI CAREER OBJECTIVE Have 2 11 years ...,IT,"SQL, ETL, Stored Procedures",[],22-08-1994,2.11,of IT experience as Database Engineer and curr...,-,-,-
3,SQL Developer,KAMBALLA PRADEEP SYNOPSIS Looking forward to a...,KAMBALLA,"SQL, Stored Procedures, Database Management",[],None,2.8,of Professional Software development experienc...,-,-,-
4,SQL Developer,Hyderabad Nazeer Basha SQL and Power BI Devel...,Hyderabad,"SQL, ETL, Stored Procedures",[10],None,2.6,Not Found,-,-,-
5,SQL Developer,Resume Name Neeraj Mishra Having 3 year 6 Mon...,Resume,"SQL, Stored Procedures","[(BE, 2013)]",None,3,6 Month of Experience on Oracle Developer.,-,-,-
6,SQL Developer,SQL DEVELOPER Name Bandi prem sai Willing to w...,SQL,"SQL, Stored Procedures, Query Optimization, Pe...","[(BCA, 2018)]",None,20,"in Microsoft SQL Server environment, with thor...",-,-,-
7,SQL Developer,SQL SERVER DEVELOPER Priyanka L Professional ...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning",[],None,2.5,of Total Experience in MICROSOFT SQL SERVER de...,-,-,-
8,SQL Developer,SQL SERVER DEVELOPER P Syam Kumar Professiona...,SQL,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2019)]",None,2.3,Not Found,-,-,-
9,SQL Developer,RAJU PAVANA KUMARI Professional Summary Havin...,RAJU,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2014)]",None,2.10,of Professional experience in SQL Server 2014/...,-,-,-
10,SQL Developer,resume Ramalakshmi K Career Objective Profess...,Ramalakshmi,"SQL, ETL, Stored Procedures, Indexing",[],None,2.5,of working experience in Microsoft SQLServer /...,-,-,-
11,SQL Developer,Name Ramesh Career Objective To contribute an ...,Ramesh,"SQL, ETL, Stored Procedures, Performance Tuning","[(10, 2018)]",None,3.5,"in system Design, Development and Support of M...",-,-,-
12,SQL Developer,Career objective A rewarding opportunity in a ...,Experience,"SQL, Stored Procedures, Performance Tuning","[(SSC, 2009)]",None,3.2,of total experience in MICROSOFT SQL SERVER De...,-,-,-
13,SQL Developer,B vinod kumar OBJECTIVE Willing to work under ...,B.,"SQL, ETL, Stored Procedures",[10],None,20,of IT Experience in Microsoft Business Intelli...,-,-,-
14,React JS Developer,Name Ravali P Curriculum Vitae Specialization ...,Ravali,,[BE],04/11/1995,20,Not Found,-,-,-
15,React JS Developer,Name SUSOVAN BAG Seeking a challenging positi...,SUSOVAN,"JavaScript, HTML, CSS",[],None,20,Not Found,-,-,-
16,React JS Developer,Kanumuru Deepak Reddy CAREER OBJECTIVE To secu...,Kanumuru,"React JS, JavaScript, JSON, React, HTML, CSS, ...","[(10, 1997)]",None,4,from MetroLabs Services Pvt Ltd.,-,-,-
17,React JS Developer,HARIPRIYA BATTINA Experience as UI Developer i...,HARIPRIYA,"React JS, JavaScript, React, HTML, CSS","[(SSC, 2012)]",None,,Not Found,9908576950,haripriyabattini@gmai.com,-
18,React JS Developer,KAMALAKAR REDDY A Linked In PROFESSIONAL SUMMA...,KAMALAKAR,"React JS, UI Development, JavaScript, React, H...",[],None,,"in UI Development of Enterprise Applications, ...",-,-,[https://www.linkedin.com/in/kamalakar-reddy-7...
19,React JS Developer,Naveen Sadhu Title software developer Locatio...,Naveen,"MERN stack, HTML, CSS",[],None,1,"of overall IT experience in Html, Sql, Reactjs...",-,-,-
20,React JS Developer,PROFILE Searching for the opportunity to brin...,PROFILE,"JavaScript, React, HTML, CSS",[],None,3,Not Found,-,-,-
21,React JS Developer,PRAGNYA PATTNAIK Expertise Having around 2 ye...,PRAGNYA,"React JS, UI Development, JavaScript, React, CSS",[10],None,2,"in UI development using Html5, CSS3, JavaScrip...",-,-,-
22,React JS Developer,204 Sri geethika prestige road number 10 band...,"Hyderabad,500090","React JS, JavaScript, React, HTML, CSS",[],None,20,in developing UI-Applications. ◉ Proﬁcient and...,-,-,-
23,React JS Developer,Thirupathamma Balla SUMMARY 2 8 year of IT ex...,Thirupathamma,"JavaScript, JSON, React",[],None,2.8,of IT experience as React Developer.,-,-,-
24,React JS Developer,Maryala Vinay Reddy Professional Summary Havin...,Maryala,"JavaScript, React, HTML, Redux",[],None,2,of successful IT experience in all phases of S...,-,-,-
25,React JS Developer,Ui Developer React JS Developer NAME KRISHNA ...,React,"React JS, JavaScript, JSON, React, HTML, CSS, ...",[],None,3.2,of Extensive experience as a React JS/Web- Dev...,-,-,-
26,React JS Developer,CURRICULUM VITAE I hereby declare that the abo...,CURRICULUM,,[],None,,Not Found,-,-,-
27,React JS Developer,Kotani Durga Prasad Objective Aspirant for a p...,Kotani,"React JS, JavaScript, JSON, React, HTML",[],None,3.1,as a Software Engineer.,-,-,-
28,React JS Developer,Venkatalakshmi Pedireddy Software Developer Ex...,Venkatalakshmi,"React JS, React","[(SSC, 2018)]",None,3,"Visakhapatnam, India",-,-,[https://batvidcoronaawareness.000webhostapp.com]
29,React JS Developer,KAMBALA SAI SURENDRA Mandepeta SUMMARY Project...,KAMBALA,"React JS, JavaScript, React, HTML, CSS, Redux",[],None,1,Not Found,-,-,-
30,React JS Developer,MAREEDU LOKESH BABU PROFESSIONAL OVERVIEW Arou...,MAREEDU,"React JS, JavaScript, React, HTML, CSS",[],None,2,"in software design, development, implementatio...",-,-,-
31,React JS Developer,MD KHIZARUDDIN RAUF EXPERIENCE Currently worki...,MD,"React JS, UI Development, JavaScript, React, H...",[10],1-06-1998,20,Not Found,-,-,-
32,React JS Developer,Name M Prabakaran Title UI Developer PROFESSI...,M.,"HTML, CSS",[],None,2.4,Not Found,-,-,-
33,React JS Developer,Pranish Sonone Career summary Experience of 1...,Pranish,"React JS, JavaScript, React, CSS, Redux",[],None,1,& 2 months working as Jr. React Developer whic...,-,-,-
34,React JS Developer,Ranga Gaganam Having 1 years of successful IT ...,Ranga,"JavaScript, React, HTML",[],None,1,Not Found,-,-,-
35,React JS Developer,SHAIK ABDUL SHARUK 2 years Experience in Wipro...,SHAIK,"React JS, React, Redux",[],None,2,’ Experience in Wipro,-,sharukabdul786@gmail.com,[https://github.com/sharukabdul/Todo-List]
36,Peoplesoft,Anubhav Kumar Singh To work in a globally com...,Anubhav,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,20,Not Found,-,-,-
37,Peoplesoft,Profile Summary 7 years of experience in impl...,Summary,"Peoplesoft, HRMS, Application Designer, Integr...",[],27/05/1987,7,Not Found,-,-,-
38,Peoplesoft,PeopleSoft Database Administrator Gangareddy P...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, SQR",[],None,4,Not Found,-,-,-
39,Peoplesoft,Murali Experience Summary I have 6 years of ex...,Experience,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6,working in PeopleSoft Administration and perfo...,-,-,-
40,Peoplesoft,Priyanka Ramadoss 61 46 MountPleasant Coonoor ...,Priyanka,"Peoplesoft, Application Designer, Integration ...",[],None,,(September 2016 - present) of experience as Pe...,-,-,-
41,Peoplesoft,PROFILE SUMMARY I have overall 6 8 years expe...,PROFILE,"Peoplesoft, HRMS, PeopleTools, Application Des...","[12th, (10th, 2015), (10, 2008)]",None,6.8,’ experience as PeopleSoft Administrator. Inst...,-,-,-
42,Peoplesoft,PEOPLESOFT Administrator SRINIVAS K Experience...,PEOPLESOFT,"Peoplesoft, HRMS, PeopleTools, SQR, Integratio...",[],None,10,Not Found,-,-,-
43,Peoplesoft,PeopleSoft Admin VARKALA VIKAS Career Objecti...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,4.2,’ Experience in PeopleSoft Admin and PeopleSof...,-,-,-
44,Peoplesoft,Vinod Akkala PeopleSoft DBA Admin Professional...,Vinod,"Peoplesoft, HRMS, PeopleTools, Integration Broker",[],None,7,Not Found,-,-,-
45,Peoplesoft,PeopleSoft Admin PeopleSoft DBA Ganesh Alladi...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,6.4,Experience in IT. With my valid expertise of 4...,-,-,-
46,Peoplesoft,PeopleSoft Administration Vivekanand Sayana Ca...,PeopleSoft,"Peoplesoft, HRMS, PeopleTools, Application Des...",[],None,7.5,"in PeopleSoft, I hope to enhance my skill set ...",-,-,-
47,Peoplesoft,Arun Venu EXPERIENCE SUMMARY Experience of 04 ...,Arun,"Peoplesoft, PeopleTools, PeopleCode, SQR",[BCA],None,20,"08 Months in multiple PeopleSoft Upgrade, Impl...",-,-,-
48,Peoplesoft,Experience Summary 4 1 years Experience of De...,Experience,"Peoplesoft, HRMS, PeopleCode, SQR",[],None,4.1,"Experience of Development, Support and mainten...",-,-,-
49,Peoplesoft,Rahul Ahuja Summary 10 2 years of experience i...,Rahul,"Peoplesoft, PeopleTools, Application Designer,...","[(10, 2019)]",None,10.2,in PeopleSoft as a Technical Consultant.,-,-,-
50,Peoplesoft,Having 4 6 years of experience in PeopleSoft ...,PeopleSoft,"Peoplesoft, Application Designer, Component In...",[],None,4.6,"in PeopleSoft application enhancement, impleme...",-,-,-
51,Peoplesoft,CAREER OBJECTIVE Pursuing Peoplesoft Executiv...,Peoplesoft,"Peoplesoft, Application Designer, PeopleCode","[(10th, 1991)]",None,3.6,in Financial Supply Chain Management and proce...,-,-,-
52,Peoplesoft,R Ahmed PeopleSoft Technical Consultant PROFE...,R,"Peoplesoft, PeopleTools, Application Designer,...",[],None,3.2,as PeopleSoft Consultant.,-,-,-
53,Peoplesoft,Tanna Sujatha OBJECTIVE Seeking a challenging ...,Tanna,Peoplesoft,"[(BTECH, 2015), (SSC, 2009)]",None,3.6,in IT. Extended expertise in PeopleSoft Financ...,-,-,-
54,Peoplesoft,C O N T A C T Address Manyata Tech Park Nagav...,Manyata,"Peoplesoft, Application Designer","[(X, 2018)]",None,,in assistance and development for projects lik...,-,-,-
55,Work Day,Chinna Subbarayudu M DOB 06th March 1994 Natio...,Chinna,"Workday, HCM, Integration, Consultant, Busines...",[],None,19,of IT experience in developing and Implementat...,-,-,-
56,Work Day,Name Gopi Krishna Reddy PROFESSIONAL SUMMERY ...,Name,"Workday, HCM, Integration, Consultant, Report ...",[],19-04-1993,3,Not Found,-,-,-
57,Work Day,Hari Krishna M Summary A result oriented profe...,Hari,"Workday, HCM, Integration, Consultant, Busines...","[(10, 2012)]",None,6.10,. of experience in Software Engineering with 3...,-,-,-
58,Work Day,Harikrishna Akula Summary 5 2 years of IT expe...,Harikrishna,"Workday, HCM, Integration, Consultant, Configu...",[],None,5.2,"of IT experience, around 3.8 years of experien...",-,-,-
59,Work Day,HIMA MENDU Career Objective To continue growin...,HIMA.MENDU,"Workday, HCM, Integration, Consultant, Busines...",[],None,20,Not Found,-,-,-
60,Work Day,G Himaja Career Objective To work towards ach...,G,"Workday, HCM, Integration, Consultant",[],None,3,of IT ERP experience which include 2+ years as...,-,-,-
61,Work Day,Name J Sumanth Royal PROFESSIONAL SUMMARY Hav...,J.,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.7,in Information Technology with 3.10 years of e...,-,-,-
62,Work Day,JYOTI VERMA 3 years of Experience in Workday ...,JYOTI,"Workday, HCM, Consultant, Business Processes, ...",[],None,3,in Workday as Functional HCM Consultant.,-,-,-
63,Work Day,Madeeswar A PROFILE SUMMARY Having around 6 y...,Madeeswar,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,of IT experience in developing and Implementat...,-,-,-
64,Work Day,Mooraboyina Guravaiah Workday Integration Spe...,Mooraboyina,"Workday, HCM, Integration, Consultant, Absence...",[],15-02-1992,5,Not Found,-,-,-
65,Work Day,Name Naresh Babu Cherukuri Objective To take u...,Babu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,Not Found,-,-,-
66,Work Day,VENKATA SAIKRISHNA Workday Consultant PROFSSIO...,VENKATA,"Workday, Consultant, Business Processes, Confi...",[],None,3,of IT experience as a Workday Consultant.,-,-,-
67,Work Day,3 3 years of IT experience as Workday HCM Tec...,IT,"Workday, HCM, Integration, Consultant",[],None,3.3,of IT experience as Workday HCM Technical Cons...,-,-,-
68,Work Day,Rahul Techno Functional Consultant Professiona...,Rahul,"Workday, HCM, Integration, Consultant, Busines...",[],None,5,"in workday HCM and Expertise in Workday HCM , ...",-,-,-
69,Work Day,Ramesh A Workday HCM Consultant PROFESSIONAL S...,Ramesh,"Workday, HCM, Consultant, Business Processes, ...",[],None,5,Not Found,-,-,-
70,Work Day,Shireesh Balasani HCM Consultant PROFILE SUMMA...,Shireesh,"Workday, HCM, Integration, Consultant, Busines...",[10],None,10,.,-,-,-
71,Work Day,Workday Integration Consultant Name Sri Krish...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,as Workday Consultant and good experience on R...,-,-,-
72,Work Day,Seeking suitable positions in Workday HCM as T...,Workday,"Workday, HCM, Integration, Consultant, Busines...",[],None,4,"in workday HCM, completed Workday Integration ...",-,-,-
73,Work Day,WORKDAY HCM FCM Name Kumar S S Role Workday C...,WORKDAY,"Workday, HCM, Integration, Consultant, Busines...",[],None,6,Not Found,-,-,-
74,Work Day,Venkateswarlu B Workday Consultant Having 5 3 ...,Venkateswarlu,"Workday, HCM, Integration, Consultant, Busines...",[],None,5.3,in IT in which 3+ years of experience in imple...,-,-,-
75,Work Day,Vinay kumar v Workday Functional Consultant E...,Vinay,"Workday, HCM, Integration, Consultant, Busines...",[],None,4.2,of Total Experience in as a Workday Functiona...,-,-,-

In [15]:
df.to_csv('Resume raw_dataset.csv')

In [16]:
df.columns

Index(['Category', 'Resume', 'Name', 'Skills', 'Education', 'DOB',
       'Experience_Years', 'Work_Experience', 'Phone', 'Email_ID', 'Links'],
      dtype='object')

In [17]:
df.head()

,Category,Resume,Name,Skills,Education,DOB,Experience_Years,Work_Experience,Phone,Email_ID,Links
0,SQL Developer,ANIL KUMAR MADDUKURI SQL MSBI Developer Summar...,ANIL,"SQL, ETL, Stored Procedures",[],None,2.4,in MS SQL Server (SSMS) and creating SSIS pack...,-,-,-
1,SQL Developer,Aradhana Tripathi Current Location Gachibowli...,Aradhana,"SQL, Stored Procedures, Database Management, D...",[],None,4,of working experience in information technolog...,-,-,-
2,SQL Developer,BUDDHA VAMSI CAREER OBJECTIVE Have 2 11 years ...,IT,"SQL, ETL, Stored Procedures",[],22-08-1994,2.11,of IT experience as Database Engineer and curr...,-,-,-
3,SQL Developer,KAMBALLA PRADEEP SYNOPSIS Looking forward to a...,KAMBALLA,"SQL, Stored Procedures, Database Management",[],None,2.8,of Professional Software development experienc...,-,-,-
4,SQL Developer,Hyderabad Nazeer Basha SQL and Power BI Devel...,Hyderabad,"SQL, ETL, Stored Procedures",[10],None,2.6,Not Found,-,-,-